In [1]:
import pandas as pd

In [35]:
customer = pd.DataFrame({
    'id' :[101,102,103],
    'name' :['roshan','vikash','prashant'],
    'score' :[45,55,65] 
})
customer

    id      name  score
0  101    roshan     45
1  102    vikash     55
2  103  prashant     65

In [4]:
pivot

name   prashant  roshan  vikash
marks      65.0    45.0    55.0

In [21]:
data = pd.DataFrame({
    'product':['Mouse','Keyboard','Mouse','Keyboard'],
    'sales':[250,350,450,620],
    'region':['East','West','East','West']
})

In [24]:
pivot = pd.pivot_table(data ,
        values='sales',
        index='product',
        aggfunc='sum',
        columns='region',
        fill_value=0,
        margins=True

)

In [25]:
pivot

region    East  West   All
product
Keyboard     0   970   970
Mouse      700     0   700
All        700   970  1670

In [32]:
crosstab = pd.crosstab(
    customer['name'],
    customer['id']
)

In [33]:
crosstab

id        101  102  103
name
prashant    0    0    1
roshan      1    0    0
vikash      0    1    0

In [ ]:
def grade(score):
    if score>=90:
        return 'A'
    if score>=80:
        return 'B'
    else:
        return 'C'

In [38]:
customer['grade']=customer['score'].apply(grade)
print(customer[['name','score','grade']])

       name  score grade
0    roshan     45     C
1    vikash     55     C
2  prashant     65     C

In [64]:
date_range = pd.date_range(
    start='2026-01-01',
    freq='MS',
    end='2026-12-1'
   
)

In [65]:
date_range

DatetimeIndex(['2026-01-01', '2026-02-01', '2026-03-01', '2026-04-01',
               '2026-05-01', '2026-06-01', '2026-07-01', '2026-08-01',
               '2026-09-01', '2026-10-01', '2026-11-01', '2026-12-01'],
              dtype='datetime64[us]', freq='MS')

In [72]:
df = pd.date_range(start='2026-01-01',periods=5,freq='D')
df_data = pd.DataFrame({
    'name':['roshan','pandey','nishad','vinay','Rahul']},index=df)
print(df_data)

              name
2026-01-01  roshan
2026-01-02  pandey
2026-01-03  nishad
2026-01-04   vinay
2026-01-05   Rahul